/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#1927d1",
        "surface-container": "#171a1f",
        "primary-container": "#8e98ff",
        "error-dim": "#d73357",
        "error-container": "#a70138",
        "on-surface-variant": "#aaabb0",
        background: "#0c0e12",
        "surface-variant": "#23262c",
        "inverse-primary": "#404dda",
        "on-error-container": "#ffb2b9",
        primary: "#9fa7ff",
        "primary-fixed-dim": "#7d88ff",
        "primary-dim": "#5764f1",
        "on-secondary-fixed-variant": "#2836da",
        surface: "#0c0e12",
        "on-secondary": "#000776",
        "surface-container-low": "#111318",
        "surface-container-high": "#1d2025",
        "on-tertiary-fixed": "#37001f",
        "on-primary": "#000c9f",
        "secondary-fixed": "#cbceff",
        "surface-bright": "#292c32",
        "surface-tint": "#9fa7ff",
        "tertiary-dim": "#ff66b3",
        error: "#ff6e84",
        "secondary-dim": "#5361ff",
        "on-tertiary-container": "#35001e",
        "on-primary-container": "#00087d",
        "surface-container-lowest": "#000000",
        "on-surface": "#f6f6fc",
        tertiary: "#ff72b6",
        "on-secondary-container": "#cacdff",
        "surface-container-highest": "#23262c",
        "inverse-surface": "#f9f9ff",
        secondary: "#8b95ff",
        "secondary-fixed-dim": "#babfff",
        "primary-fixed": "#8e98ff",
        "inverse-on-surface": "#53555a",
        "on-secondary-fixed": "#000fb0",
        "tertiary-container": "#fe54ad",
        "tertiary-fixed-dim": "#ff72b6",
        "on-tertiary": "#4f002f",
        "on-primary-fixed-variant": "#000b98",
        "on-background": "#f6f6fc",
        outline: "#74757a",
        "outline-variant": "#46484d"
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
    },
  },
};

