[frontend]
frontend-vm ansible_host=10.0.1.27

[backend]
backend-vm ansible_host=127.0.0.1 ansible_connection=local

[auth]
auth-vm ansible_host=10.0.3.158

[search]
search-vm ansible_host=10.0.2.26

[realtime]
realtime-vm ansible_host=10.0.3.180

[all:vars]
ansible_user=deploy
