- name: Configure common deploy prerequisites
  hosts: all
  become: true
  roles:
    - common

- name: Configure and deploy realtime VM
  hosts: realtime
  become: true
  roles:
    - realtime
    
- name: Configure and deploy backend VM
  hosts: backend
  become: true
  roles:
    - backend

- name: Configure and deploy frontend VM
  hosts: frontend
  become: true
  roles:
    - frontend

- name: Configure and deploy search VM
  hosts: search
  become: true
  roles:
    - search

