- name: Configure common deploy prerequisites
  hosts: all
  become: true
  roles:
    - common

- name: Configure and deploy realtime VM
  hosts: realtime
  become: true
  roles:
    - realtime

- name: Configure and deploy messages VM
  hosts: messages
  become: true
  roles:
    - messages

- name: Configure and deploy dms VM
  hosts: dms
  become: true
  roles:
    - dms

- name: Configure and deploy auth VM
  hosts: auth
  become: true
  roles:
    - auth
    
- name: Configure and deploy backend VM
  hosts: backend
  become: true
  roles:
    - backend

- name: Configure and deploy frontend VM
  hosts: frontend
  become: true
  roles:
    - frontend

- name: Configure and deploy search VM
  hosts: search
  become: true
  roles:
    - search

